### ISSUE TITLE
Upgrade to 0.29

### ISSUE THREAD

**Issue by crowbot** [mysociety/belgium-theme#61]
Main reason for doing this is to be able to apply https://github.com/mysociety/alaveteli/tree/locale-filter-fix as a hotfix

## To-do
- [x] Check overridden templates for `<%= flash[:notice] %>`
- [x] Check template changes
- [x] Get translations updated
- [x] Test locally

## Deploy to-do list
- [x] Migrate `COOKIE_STORE_SESSION_SECRET` value to `SECRET_KEY_BASE`
- [x] Deploy
- [x] Run `bundle exec rake temp:cache_delivery_status`
- [x] Run `bundle exec rake db:seed`
- [x] Run `bundle exec rake temp:migrate_admins_and_pros_to_roles`
- [x] Run `bundle exec rake temp:remove_line_breaks_from_request_titles`
- [x] Run `bundle exec rake temp:generate_request_summaries`
- [x] Run `bundle exec rake temp:set_use_notifications`

**Comment by crowbot** [comment]
I don't _think_ there are any code changes needed here. Probably worth a quick double-check from someone more familiar with the theme though.

**Comment by lizconlan** [comment]
I've had a quick look through and I can't see any need for code changes either so should be ok!

**Comment by lizconlan** [comment]
(Arguably the wording for the very overdue email template has changed a bit the current wording is at their request so not sure about that one)
